### ISSUE TITLE
Not getting _gh2.bat file after running _init_repo.bat

### ISSUE THREAD

**Issue by Phoenix21938** [hmxmilohax/Guitar-Hero-II-Deluxe-360#12]
So, I wiped my pc, forgot to reinstall git so I realise I'd never updated, unable to use the input display etc. Installed git, ran the bat to update, had a few files causing issues, deleted them and ran and it updated. It never redownloaded some of the files so I just decided to completely reinstall. 

Went to Alec's vid, went to the link in the description to download, ran that. I now A. have way more files than he does (presumably just because his vid is quite old now) and B. Don't have the _gh2.bat file to be able to run the game. I'll link a screenshot of the files I do have. 

JakeCH on twitter if it's easier to message there
![image](https://user-images.githubusercontent.com/69173248/212525679-76a96f00-49e3-4fb7-9ce3-ab6c581f8da3.png)

**Comment by jnackmclain** [comment]
Yes. Alecs video is very old at this point. Things have gone through several iterations by this point and don't match up with that video. _gh2.bat is now replaced with the scripts that start with _build.
_build_xenia.bat will build the game and launch in Xenia, as _gh2.bay previously did. This is all covered in the readme of this repo.

**Comment by Phoenix21938** [comment]
Ohhhh my bad, thank you. Shouldn't have followed an old vid
