### ISSUE TITLE
Can't find init.dta

### ISSUE THREAD

**Issue by Phoenix21938** [hmxmilohax/Guitar-Hero-II-Deluxe-360#13]
So, I assumed Alecs vid was outdated this time and checked the release. It still says to go to init.dta to set your changes and have them saves. I only have init_dev.dta. I checked through the files on github to see how they're labelled and I'm not seeing one that says it's for setting your modifiers. Which file has this been moved to?

**Comment by jnackmclain** [comment]
at the root of the repo. in the folder _init
