### ISSUE TITLE
[Feature Request] Ability to change xex Title ID

### ISSUE THREAD

**Issue by syboxez** [hmxmilohax/Guitar-Hero-II-Deluxe-360#25]
Hello. I would like to change the Title ID for the 360 version of GH2DX, since right now, the DLC conflicts with vanilla GH2. I would like to have a separate vanilla game and GH2DX.

Attempting to use [TitleID changer](https://github.com/Gualdimar/TitleID-Changer) on default.xex causes the game to crash on launch. The regular default.xex works fine.
I'm using real hardware if that makes a difference.

**Comment by lunalawl** [comment]
We will not be changing the xex title ID or name to avoid issues or bans on xbox live

**Comment by syboxez** [comment]
Is there a way to do this manually? I don't use Xbox Live.
