### ISSUE TITLE
[Feature Request] Adjust audio lag separately from video lag

### ISSUE THREAD

**Issue by syboxez** [hmxmilohax/Guitar-Hero-II-Deluxe-360#26]
This is a feature in newer GH/RB games and in CH. It would be a very useful feature for both console and for PC using Xenia or PCSX2. It is especially useful when video lag is near-zero already, which is a fairly common situation nowadays.

For example, enabling Dolby Audio on 360 hardware causes audio lag in many setups. While disabling it does remove the audio lag, having an option to adjust audio lag in-game would allow for the enablement of Dolby Audio while still having a playable experience.

On PC, all sorts of different setups can cause audio lag. The lowest I can get on Windows is 120ms with one of my DACs and 200ms with the other one. Haven't tested on Linux due to the XInput requirement on Xenia, and my controller's buttons not mapping correctly.

**Comment by lunalawl** [comment]
would require modifying the game's source code, not possible
