### ISSUE TITLE
Custom songs on console

### ISSUE THREAD

**Issue by ezio416** [hmxmilohax/Guitar-Hero-II-Deluxe-360#7]
I set up my RGH 360 and the game runs on it with just the base song, Speed Test. I'm having trouble trying to import custom songs. The songs work fine in Xenia (GH2 setlist and a custom I converted in Onyx & C3ConTools).

I've tried:
- copying the "content" folder to the console
- putting the songs in "_ark/songs" and building, then replacing the "gen" folder on the console
- editing "_ark/config/songs.dta" to include the custom song

What could I be missing here? On the console I only have content, gen, and default.xex.

**Comment by LlysiX** [comment]
you need to have the songs in LIVE format
I also believe you are using the wrong content folder, as 360s have one at the root of the hard drive, not inside game folders

**Comment by ezio416** [comment]
I've tried the LIVE format still with no luck. The root content folder is for standard (non-RGH) storage and I have nothing there but an optional media update

**Comment by LocalH** [comment]
The LIVE files go in Hdd1:/Content/0000000000000000/415607E7/00000002

GH2 does not support CON formatted content.

**Comment by ezio416** [comment]
Creating that directory was what I needed, thank you guys! Thanks for the extra info too
